# Docker comes pre installed in the Github VM.
name: Using_Containers
on: push
jobs:
  docker-multiple-containers-STEPS:
    runs-on: ubuntu-latest
    container:
      # Dummy comment here
      image: node:17-alpine
    steps:
      - name: Log node version
        run: node -v
    # steps:
    #   - name: Step with docker container
    #     # The uses keyword can be used with actions or docker containers
    #     uses: docker://node:alpine-17
    #     # The with keyword is used to add input
    #     with:
    #       # works exactly as the entrypoint keyword in a docker file
    #       entrypoint: /bin/echo
    #       # This would act like the CMD command to add more parameters to the entrypoint command.
    #       args: Hello World

    #   - name: Another step with another docker container
    #     # The uses keyword can be used with actions or docker containers
    #     uses: docker://node:alpine-17
    #     # The with keyword is used to add input
    #     with:
    #       # works exactly as the entrypoint keyword in a docker file
    #       entrypoint: /usr/local/bin/node
    #       # This would act like the CMD command to add more parameters to the entrypoint command.
    #       args: -v

  docker-single-container-JOB:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine
      ports:
        - 3000
      env:
        myVariable: 'This is my variable'
      #? volumes:
      #?   - "sdfd"
    steps:
      - name: Log node version
        run: node -v

  docker-multiple-containers-JOB:
    runs-on: ubuntu-latest
    # The syntax is like docker-compose
    services:
      myClientApp:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      # Github creates automatically a network between the containers
      # The url connection to this mongoDB service must be mongo instead of localhost here below the name of the service is specified as mongo (in the app the connection url points to the mongo service)
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Testing a Post a user
        run: |
          curl --request POST \
          --header 'content-type: application/json' \
          --data '{"username": "Hello", "address": "World"}' \
          --url http://localhost:3001/api/user

      - name: Testing a GET request
        run: |
          curl --request GET \
          --header 'content-type: application/json' \
          --url http://localhost:3001/api/users
