# Github store values in objects that are called CONTEXTS
#! The ${{}} syntax
# This evaluates an expression, it can be a boolean, calculation, function, value of a object
#* REMEMBER
# Transforming and object to JSON is the way to deeply clone nexted objects.
# It is also a way to display deeply nestes objects in the console.
name: Github Contexts Objects
on:
  push:
    branches:
      - master
jobs:
  # There are more contexts than those.
  # https://docs.github.com/en/actions/learn-github-actions/contexts
  Dump_Contexts_Objects:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Context
        env:
          GITHUB: ${{ toJson(github) }}
        run: |
          echo "GITHUB CONTEXT - ${GITHUB}"
          echo ${{ github.event.client_payload.env }}

      - name: Dump Job Context
        env:
          JOB: ${{ toJson(job) }}
        run: echo "JOB CONTEXT - ${JOB}"

      - name: Dump Steps Context
        env:
          # To access the steps context the step must have and ID
          STEPS: ${{ toJson(steps) }}
        run: echo "STEPS CONTEXT - ${STEPS}"

      - name: Dump Runner Context
        env:
          RUNNER: ${{ toJson(runner) }}
        run: echo "RUNNER CONTEXT - ${RUNNER}"

      - name: Dump Strategy Context
        env:
          STRATEGY: ${{ toJson(strategy) }}
        run: echo "STRATEGY CONTEXT - ${STRATEGY}"

      - name: Dump Matrix Context
        env:
          MATRIX: ${{ toJson(matrix) }}
        run: echo "MATRIX CONTEXT - ${MATRIX}"
