name: Github Actions Functions
on:
  push:
    branches:
      - master
  pull_request:
    # Triggering the jobs by pull requests events.
    types: [closed, assigned, opened, reopened]
    # Triggering the jobs by specific branches
    branches:
      - master
jobs:
  Functions_Examples:
    runs-on: ubuntu-latest
    # All other dependent jobs will continue if this job fails
    continue-on-error: true
    #! This is an evaluation express just like the ${{}}
    # The ${{}} syntax is not needed here
    # The if evalutation expression can also be used inside the steps
    if: github.event_name == 'push'
    steps:
      - name: Functions
        run: |
          echo ${{ contains( 'hello', 'll') }}
          echo ${{ startsWith( 'hello', 'he') }}
          echo ${{ endsWith( 'hello', 'lo') }}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!') }}

      - name: Run if previous step SUCCED
        if: success()
        run: echo "Previous step succed"

      - name: Step Meant to fail
        run: eccho "Meant to fail"
        #! If THIS STEP FAILS all other will continue normally
        continue-on-error: true

      - name: Run if previous step fail
        # This function is made to run a step if the previous failed
        if: failure()
        run: echo "Previous step failed"

      - name: Always run
        # This function is made to run a step if the previous failed
        if: always()
        run: echo "This step will always regardlees of what happens in the workflow"

        # This must not run because we have failed steps in the job
      - name: This is step must not run except if continue on error exists
        run: echo "Continue on error exists"

  Useful_Commands:
    runs-on: ubuntu-latest
    # Makes the jobs run in a desired sequence.
    needs: ['Functions_Examples']
    # Can wait for multiple jobs since it is an array
    # needs: ['Function_Examples']
    if: github.event_name == 'push'
    steps:
      - name: This is not suppose to because of failure in one of the previous job
        run: echo Simple Example
