# Github Actions run every job in a different virtual machine created specially for it.
# Is possible to run jobs sequentially or simultaneasly

#! EXAMPLE TO RUN TERMINAL COMMANDS
# Name of the github workflow that will be displayed in Github Actions
name: Shell Commands
# Array of events in which a specific job will be performed
# Can also be a object
on: 
  pull_request:
  workflow_dispatch:
   inputs:
     string:
       description: A string input
       type: string
       required: false
       default: A default value
# Jobs is an object and a name must be given to the object key.
jobs:
  # Name of the job
  run-shell-command:
    # Operating system in which the virtual machine will run
    # In a linux OS the shell is automatically bash
    runs-on: ubuntu-latest
    # Steps that will take place. In this case some simple bash commands
    steps:
      # Name of the command
      - name: echo a script
        # Command itself
        run: echo Hello World
      - name: multiline script
        run: | # The pipe symbols allows to run multiple commands
          node -v
          npm -v
      - name: pythons commands
        run: |
          import platform
          print(platform.processor())
        # Specifying the shell
        shell: python
  # Name of the second job
  run-windows-commands:
    runs-on: windows-latest
    # Will only run after the jobs listed inside this array
    needs: ['run-shell-command']
    steps:
      - name: echo a bash script in windows
        run: echo bash script in a windows machine
        shell: bash
      - name: get location in power shell
        run: Get-Location
      - name: PWD
        run: pwd
        shell: bash
