name: Workflow Environment Variables

on:
  push:
    branches:
      - master

env:
  WF_ENV: Available for all jobs

jobs:
  workflow_env_variables:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available only in THIS JOB
    steps:
      - name: Read the self configured environment variables
        env:
          STEP_ENV: Available only in this STEP
        run: |
          echo "WL_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
