name: Workflow Environment Variables

on:
  push:
    branches:
      - master
# Environment variable has scopes. It can be global, job scoped or step scoped.
env:
  WF_ENV: Available for all jobs
  #! You can also set the environment variables inside Github by using the secrets configurations inside the repository.
  #! <username>/<repository>/settings/secrets/actions
  WF_ENV_FROM_GITHUB: ${{ secret.WF_ENV_FROM_GITHUB }}

jobs:
  workflow_env_variables:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available only in THIS JOB
    steps:
      - name: Read the self configured environment variables
        env:
          STEP_ENV: Available only in this STEP
        run: |
          echo "WL_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
