name: Workflow Environment Variables

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [build]
# Environment variable has scopes. It can be global, job scoped or step scoped.
env:
  WF_ENV: Available for all jobs
  # Environment variables can be set inside Github's repository.
  # Those variables are encripted
  #! <username>/<repository>/settings/secrets/actions
  WF_ENV_FROM_GITHUB: ${{ secrets.WF_ENV_FROM_GITHUB }}

jobs:
  workflow_env_variables:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available only in THIS JOB
    steps:
      - name: Self configured in file environment variables
        env:
          STEP_ENV: Available only in this STEP
        run: |
          echo "WL_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          echo "${{ github.event.client_payload.env }}"
      - name: Self configured in Github env variables
        run: |
          echo "WF_ENV_FROM_GITHUB: ${{ secrets.WF_ENV_FROM_GITHUB }}"
          echo "${{ github.event.client_payload.env }}"
